name: "build-dockerfile"
on: [push]
jobs:
  docker-build:
    runs-on: efrondev/test-runpod-runner
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: checkout
        uses: actions/checkout@v4

      - name: generate-config-if-necessary
        run: |
          /app/configure-github-action
      - name:

      # Build and push step
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ vars.DOCKERHUB_REPO }}/${{ vars.DOCKERHUB_IMG }}:${{ (github.event_name == 'release' && github.event.release.tag_name) || (github.event_name == 'workflow_dispatch' && github.event.inputs.image_tag) || 'dev' }}

      - name: deploy-endpoint
        run: |
          runpodctl project deploy --mode=dockerfile